import React, { useState } from 'react';
import { usePocket } from '../context/PocketContext';
import { X, Trash2, Download, Copy, Check, ShoppingBag, ExternalLink } from 'lucide-react';

export const PocketBasketDrawer: React.FC = () => {
  const {
    isBasketOpen,
    setIsBasketOpen,
    savedItems,
    removeItem,
    clearItems,
    formatPrice,
    totalSavedCostINR,
    currency,
  } = usePocket();

  const [copied, setCopied] = useState(false);

  if (!isBasketOpen) return null;

  const handleExportCSV = () => {
    if (savedItems.length === 0) return;
    const headers = ['Item Name', 'Category', 'Source Planner', 'Estimated Price (INR)', 'Date Added'];
    const rows = savedItems.map((item) => [
      `"${item.name.replace(/"/g, '""')}"`,
      `"${item.category}"`,
      `"${item.source.toUpperCase()}"`,
      item.price,
      `"${new Date(item.addedAt).toLocaleDateString()}"`,
    ]);
    const csvContent = 'data:text/csv;charset=utf-8,' + [headers.join(','), ...rows.map((e) => e.join(','))].join('\n');
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', `pocketsmart-plan-${Date.now()}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleCopySummary = () => {
    if (savedItems.length === 0) return;
    const text = [
      `--- PocketSmart AI Procurement Plan ---`,
      `Total Items: ${savedItems.length}`,
      `Total Cost: ${formatPrice(totalSavedCostINR)} (${currency})`,
      `---------------------------------------`,
      ...savedItems.map(
        (it, idx) => `${idx + 1}. ${it.name} [${it.category}] - ${formatPrice(it.price)}`
      ),
      `---------------------------------------`,
      `Generated by PocketSmart AI`,
    ].join('\n');
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 overflow-hidden">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-slate-950/80 backdrop-blur-xs transition-opacity"
        onClick={() => setIsBasketOpen(false)}
      />

      <div className="fixed inset-y-0 right-0 max-w-full flex pl-10">
        <div className="w-screen max-w-md bg-[#1E293B] shadow-2xl flex flex-col border-l border-slate-800">
          {/* Header */}
          <div className="p-5 border-b border-slate-800 flex items-center justify-between bg-[#0F172A] text-[#F8FAFC]">
            <div className="flex items-center gap-2.5">
              <div className="w-8 h-8 rounded-lg bg-[#7C3AED] text-[#F8FAFC] flex items-center justify-center font-bold shadow-md shadow-purple-600/30">
                <ShoppingBag className="w-4 h-4" />
              </div>
              <div>
                <h2 className="text-base font-bold text-[#F8FAFC]">Pocket Basket</h2>
                <p className="text-xs text-[#94A3B8]">
                  {savedItems.length} {savedItems.length === 1 ? 'item' : 'items'} pinned
                </p>
              </div>
            </div>
            <button
              onClick={() => setIsBasketOpen(false)}
              className="p-1.5 rounded-lg text-[#94A3B8] hover:text-[#F8FAFC] hover:bg-slate-800 transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          {/* Subtotal Banner */}
          <div className="bg-[#172033] border-b border-slate-800 px-5 py-3 flex items-center justify-between">
            <span className="text-xs font-semibold text-[#94A3B8] uppercase tracking-wider">
              Cumulative Estimated Cost
            </span>
            <span className="text-lg font-black text-[#F8FAFC] font-mono tabular-nums">
              {formatPrice(totalSavedCostINR)}
            </span>
          </div>

          {/* Item List */}
          <div className="flex-1 overflow-y-auto p-5 space-y-3">
            {savedItems.length === 0 ? (
              <div className="h-full flex flex-col items-center justify-center text-center p-6 text-slate-500">
                <ShoppingBag className="w-12 h-12 stroke-[1.2] mb-3 text-slate-600" />
                <h3 className="text-sm font-bold text-[#F8FAFC]">Your basket is empty</h3>
                <p className="text-xs text-[#94A3B8] mt-1 max-w-xs">
                  Click the bookmark/pin icon on any recommended fixture, venue, or jewelry piece to build your procurement plan.
                </p>
              </div>
            ) : (
              savedItems.map((item) => (
                <div
                  key={item.id}
                  className="p-3.5 rounded-xl border border-slate-800/80 bg-[#0F172A] hover:border-purple-500/30 transition-all flex flex-col gap-2"
                >
                  <div className="flex items-start justify-between gap-2">
                    <div>
                      <span className="text-[10px] font-bold text-[#A78BFA] uppercase tracking-wider">
                        {item.source} · {item.category}
                      </span>
                      <h4 className="text-xs font-bold text-[#F8FAFC] line-clamp-2 mt-0.5">
                        {item.name}
                      </h4>
                    </div>
                    <button
                      onClick={() => removeItem(item.id)}
                      className="text-slate-500 hover:text-[#EF4444] p-1 transition-colors shrink-0"
                      title="Remove item"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                  </div>

                  <div className="flex items-center justify-between pt-1 border-t border-slate-800/80 text-xs">
                    <span className="font-bold text-[#F8FAFC] font-mono tabular-nums">
                      {formatPrice(item.price)}
                    </span>
                    {item.shoppingLinks && Object.keys(item.shoppingLinks).length > 0 && (
                      <div className="flex items-center gap-1.5">
                        {Object.entries(item.shoppingLinks).slice(0, 3).map(([platform, url]) => (
                          <a
                            key={platform}
                            href={url}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="text-[10px] font-semibold text-[#38BDF8] hover:underline capitalize flex items-center gap-0.5"
                          >
                            <span>{platform}</span>
                            <ExternalLink className="w-2.5 h-2.5" />
                          </a>
                        ))}
                      </div>
                    )}
                  </div>
                </div>
              ))
            )}
          </div>

          {/* Footer Actions */}
          {savedItems.length > 0 && (
            <div className="p-5 border-t border-slate-800 bg-[#0F172A] space-y-2.5">
              <div className="grid grid-cols-2 gap-2">
                <button
                  onClick={handleExportCSV}
                  className="py-2 px-3 rounded-xl border border-purple-500/30 bg-[#1E293B] hover:bg-slate-700/60 text-[#A78BFA] text-xs font-bold flex items-center justify-center gap-1.5 transition-colors"
                >
                  <Download className="w-3.5 h-3.5" />
                  <span>Export CSV</span>
                </button>
                <button
                  onClick={handleCopySummary}
                  className="py-2 px-3 rounded-xl border border-purple-500/30 bg-[#1E293B] hover:bg-slate-700/60 text-[#A78BFA] text-xs font-bold flex items-center justify-center gap-1.5 transition-colors"
                >
                  {copied ? (
                    <>
                      <Check className="w-3.5 h-3.5 text-[#22C55E]" />
                      <span className="text-[#22C55E]">Copied!</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-3.5 h-3.5" />
                      <span>Copy Plan</span>
                    </>
                  )}
                </button>
              </div>

              <button
                onClick={clearItems}
                className="w-full py-1.5 text-center text-[11px] font-semibold text-slate-500 hover:text-[#EF4444] transition-colors"
              >
                Clear all saved items
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
